name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '22 21 * * *'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_RULES: "p/default custom-semgrep-rules-dir/"
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4

      - name: Semgrep scan
        id: scan
        run: semgrep ci --config=auto --sarif -o result.sarif

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result.sarif
          path: result.sarif